# Generated by Django 5.0.4 on 2025-04-06 10:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('max_players', models.IntegerField(default=2)),
                ('map_size', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)])),
                ('map_data', models.JSONField(default=dict)),
                ('current_turn', models.IntegerField(default=1)),
                ('current_player_index', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('resources', models.JSONField(blank=True, default=dict, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['player_number'],
                'unique_together': {('game', 'player_number')},
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('health', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building_type', models.CharField(choices=[('base', 'Base'), ('barracks', 'Barracks'), ('farm', 'Farm'), ('mine', 'Mine')], max_length=20)),
                ('resource_production', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='game.player')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('health', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit_type', models.CharField(choices=[('infantry', 'Infantry'), ('archer', 'Archer'), ('cavalry', 'Cavalry'), ('siege', 'Siege Engine')], max_length=20)),
                ('attack', models.PositiveIntegerField(default=10)),
                ('defense', models.PositiveIntegerField(default=5)),
                ('movement_range', models.PositiveIntegerField(default=2)),
                ('attack_range', models.PositiveIntegerField(default=1)),
                ('has_moved', models.BooleanField(default=False)),
                ('has_attacked', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='game.player')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='game.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
            options={
                'ordering': ['turn_number', 'player'],
                'unique_together': {('game', 'player', 'turn_number')},
            },
        ),
    ]
