# Generated by Django 5.0.2 on 2025-03-21 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("current_turn", models.IntegerField(default=1)),
                ("max_players", models.IntegerField(default=2)),
                ("map_size", models.IntegerField(default=10)),
                ("map_data", models.TextField(default="{}")),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resources", models.IntegerField(default=100)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("player_number", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="game.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "game")},
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "building_type",
                    models.CharField(
                        choices=[
                            ("base", "Base"),
                            ("barracks", "Barracks"),
                            ("farm", "Farm"),
                            ("mine", "Mine"),
                        ],
                        max_length=20,
                    ),
                ),
                ("x_position", models.IntegerField()),
                ("y_position", models.IntegerField()),
                ("health", models.IntegerField(default=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buildings",
                        to="game.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("infantry", "Infantry"),
                            ("archer", "Archer"),
                            ("cavalry", "Cavalry"),
                            ("siege", "Siege Engine"),
                        ],
                        max_length=20,
                    ),
                ),
                ("x_position", models.IntegerField()),
                ("y_position", models.IntegerField()),
                ("health", models.IntegerField(default=100)),
                ("attack", models.IntegerField(default=10)),
                ("defense", models.IntegerField(default=5)),
                ("movement_range", models.IntegerField(default=2)),
                ("attack_range", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="game.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Turn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turn_number", models.IntegerField()),
                ("actions", models.TextField(default="[]")),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="game.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.player"
                    ),
                ),
            ],
            options={
                "unique_together": {("game", "player", "turn_number")},
            },
        ),
    ]
