# Generated by Django 5.0.2 on 2025-03-23 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="building",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="player",
            options={"ordering": ["player_number"]},
        ),
        migrations.AlterModelOptions(
            name="turn",
            options={"ordering": ["turn_number", "created_at"]},
        ),
        migrations.AlterModelOptions(
            name="unit",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="player",
            unique_together={("user", "game")},
        ),
        migrations.AddField(
            model_name="building",
            name="resource_production",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="has_attacked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="unit",
            name="has_moved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="building",
            name="health",
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AlterField(
            model_name="building",
            name="x_position",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="building",
            name="y_position",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="game",
            name="map_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="game",
            name="map_size",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="game",
            name="max_players",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="player",
            name="player_number",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="player",
            name="resources",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="turn",
            name="actions",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="turn",
            name="turn_number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="unit",
            name="attack",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="unit",
            name="attack_range",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="unit",
            name="defense",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="unit",
            name="health",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="unit",
            name="movement_range",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="unit",
            name="x_position",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="unit",
            name="y_position",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="player",
            unique_together={("game", "player_number"), ("user", "game")},
        ),
    ]
