# Generated by Django 5.0.2 on 2025-03-25 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_alter_building_options_alter_game_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="resources",
        ),
        migrations.AddField(
            model_name="game",
            name="current_player_index",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="game_state",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="building",
            name="health",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="building",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="game.player",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="game.player",
            ),
        ),
    ]
