# Generated by Django 5.0.2 on 2025-04-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_alter_game_map_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="resources",
            field=models.IntegerField(default=100),
        ),
    ]
