# Generated by Django 5.0.2 on 2025-04-06 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_remove_game_map_size_alter_game_map_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="map_size",
            field=models.CharField(
                default=10,
                max_length=20,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
    ]
