# Generated by Django 5.0.2 on 2025-04-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_game_map_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="resources",
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
